# P02_survey

## Program to obtain descriptive statistics of the responses from the applied questionnaire.

### Create a new DataFrame from file with the students' responses to the questionnaire and file with variable "IT Industry 4.0 Knowledge" (k)

In [1]:
import numpy as np
import pandas as pd
from scipy import stats
from scipy import signal
from scipy.stats import norm
from scipy.stats import pearsonr
import statistics
import math
from pathlib import Path

ruta_entrada = Path('..')/'Datasets'/'enc_datosnum.csv'
df = pd.read_csv(ruta_entrada,delimiter=",",encoding = "ISO-8859-1")
data = pd.DataFrame(df)

ruta_entrada = Path('..')/'Datasets'/'KI4.csv'
df2 = pd.read_csv(ruta_entrada,delimiter=",",encoding = "ISO-8859-1")
dfki4 = pd.DataFrame(df2)

dconcat = pd.concat([data,dfki4], axis=1)

#Export DataFrame dconcat as a file named dconcat.csv.
ruta_salida = Path('..')/'Datasets'/'dconcat.csv'
dconcat.to_csv(ruta_salida, index=False)

In [2]:
dconcat

,Genero,P01,P02,P03,P04,P05,P06,P07,P08,P09,...,P21,P22,P23,P24,P25,P26,P27,P28,k,kr
0,1,1,2,4,2,1,1,3,3,3,...,1,1,2,3,2,4,1,1,1.974938,2
1,1,1,2,4,2,1,1,3,3,3,...,1,1,2,3,2,4,1,1,1.974938,2
2,1,1,2,4,3,1,1,4,3,3,...,2,2,2,3,2,4,1,1,2.494682,2
3,1,1,2,4,3,1,1,4,4,3,...,2,2,2,3,2,4,1,1,2.494682,2
4,1,1,2,4,3,1,1,4,4,4,...,3,2,2,4,2,4,1,1,3.113947,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,2,2,2,3,5,2,2,5,5,5,...,4,4,4,5,4,5,1,1,4.236525,4
108,2,2,2,3,5,2,2,5,5,5,...,4,5,4,5,4,5,3,3,4.638411,4
109,2,2,4,5,5,3,3,5,5,5,...,5,5,4,5,4,5,3,3,4.771877,5
110,2,2,1,5,5,3,3,5,5,5,...,5,5,4,5,4,5,3,3,4.771877,5
111,3,2,1,5,5,3,3,5,5,5,...,5,5,4,5,4,5,3,3,4.771877,5

## Descriptive statistics

In [3]:
import pandas as pd
import numpy as np
from scipy.stats import skew, kurtosis

df = dconcat

# Function to obtain descriptive statistics
def calcular_estadisticas(df):
    resultados = {}
    
    for columna in df.columns:
        datos = df[columna]
        if columna == 'ï»¿K':
            continue
       
        estadisticas = {
            'Mean': datos.mean(),
            'Median': datos.median(),
            'Mode': datos.mode()[0],  # There can be multiple modes; we take the first one
            'Standard Deviation': datos.std(),
            'Variance': datos.var(),
            'Skewness': skew(datos),
            'Standar error of Skewness': np.sqrt(6 / len(datos)),  # Standard error approximation of skewness
            'Kurtosis': kurtosis(datos),
            'Range': datos.max() - datos.min()
        }
        
        resultados[columna] = estadisticas
    
    return pd.DataFrame(resultados)

# Obtain the descriptive statistics
estadisticas_df = calcular_estadisticas(df)

# Dispay descriptive statistics
print(estadisticas_df)

                             Genero       P01       P02       P03       P04  \
Mean                       1.794643  1.401786  3.392857  3.964286  4.089286
Median                     2.000000  1.000000  4.000000  4.000000  4.000000
Mode                       2.000000  1.000000  4.000000  4.000000  5.000000
Standard Deviation         0.486547  0.492462  1.289997  0.985741  1.009447
Variance                   0.236728  0.242519  1.664093  0.971686  1.018983
Skewness                  -0.458974  0.400663 -0.507935 -0.778874 -0.865495
Standar error of Skewness  0.231455  0.231455  0.231455  0.231455  0.231455
Kurtosis                   0.139301 -1.839469 -0.788766 -0.348571 -0.376086
Range                      2.000000  1.000000  4.000000  3.000000  3.000000

                                P05       P06       P07       P08       P09  \
Mean                       1.419643  1.500000  4.446429  4.214286  4.446429
Median                     1.000000  1.000000  5.000000  4.000000  5.000000
Mode                       1.000000  1.000000  5.000000  5.000000  5.000000
Standard Deviation         0.652623  0.771100  0.682329  0.787613  0.825705
Variance                   0.425917  0.594595  0.465573  0.620335  0.681789
Skewness                   1.276382  1.125040 -0.831167 -0.395764 -0.985718
Standar error of Skewness  0.231455  0.231455  0.231455  0.231455  0.231455
Kurtosis                   0.395703 -0.377410 -0.489782 -1.273032 -0.798897
Range                      2.000000  2.000000  2.000000  2.000000  2.000000

                           ...       P21       P22       P23       P24  \
Mean                       ...  3.062500  2.723214  2.767857  4.107143
Median                     ...  3.000000  3.000000  3.000000  4.000000
Mode                       ...  3.000000  2.000000  2.000000  4.000000
Standard Deviation         ...  1.084545  1.100449  0.782490  0.739578
Variance                   ...  1.176239  1.210988  0.612291  0.546976
Skewness                   ... -0.251887  0.441336  0.429391 -0.171202
Standar error of Skewness  ...  0.231455  0.231455  0.231455  0.231455
Kurtosis                   ... -0.287706 -0.343847 -1.234615 -1.144083
Range                      ...  4.000000  4.000000  2.000000  2.000000

                                P25       P26       P27       P28         k  \
Mean                       2.973214  4.339286  1.232143  1.232143  3.350771
Median                     3.000000  4.000000  1.000000  1.000000  3.370658
Mode                       3.000000  4.000000  1.000000  1.000000  3.113947
Standard Deviation         0.810514  0.475595  0.643500  0.643500  0.759209
Variance                   0.656934  0.226190  0.414093  0.414093  0.576398
Skewness                   0.048638  0.678883  2.397227  2.397227 -0.121496
Standar error of Skewness  0.231455  0.231455  0.231455  0.231455  0.231455
Kurtosis                  -1.462525 -1.539118  3.746698  3.746698 -0.664951
Range                      2.000000  1.000000  2.000000  2.000000  2.796938

                                 kr
Mean                       3.160714
Median                     3.000000
Mode                       3.000000
Standard Deviation         0.800378
Variance                   0.640605
Skewness                   0.022085
Standar error of Skewness  0.231455
Kurtosis                  -0.826971
Range                      3.000000

[9 rows x 31 columns]